language: node_js
node_js: 11
cache: npm
sudo: required
addons:
  chrome: stable
os:
  - linux
  - osx

env:
global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

install:
  # Install all dependencies listed in your package.json file
  - yarn install --force

script:
  - echo "Tests"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run npm run test; else npm run test; fi
